### ISSUE TITLE
Product option URLs are not respected when loading PDP

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#321] opened 2018-09-21 00:14 UTC
When changing an option selected, e.g. from "Small" to "Large" the url state is updated. 

If you attempt to load the page from that url, the default option is automatically selected.

<img src="http://g.recordit.co/iu6PMFPA8P.gif" />

**Comment by machikoyasuda** [comment] 2018-11-20 19:07
Closing b/c duplicate of this ticket https://github.com/reactioncommerce/reaction-next-starterkit/issues/408

**Closed by machikoyasuda** 2018-11-20 19:07 UTC
Labels: bug
