### ISSUE TITLE
Product Grid Filters display incorrectly

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-next-starterkit#260] opened 2018-09-04 21:24 UTC
## Summary
I'm seeing an issue where the filters that sit above the product grid are getting aligned-left instead of right and the margins are not correct.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/1203639/45058668-9481a300-b056-11e8-863b-17029abd6063.png">

**Comment by mikemurray** [comment] 2018-09-04 22:29
When locally it looks fine, so it might be related to the production build.

![screen shot 2018-09-04 at 1 16 54 pm](https://user-images.githubusercontent.com/42217/45060955-2a1d3280-b057-11e8-940c-00da43b4027e.png)

**Comment by aldeed** [comment] 2018-09-04 22:45
Seems to be fixed in the new staging build. @spencern or @mikemurray can you confirm it's fixed for you, too?

**Comment by aldeed** [comment] 2018-09-04 23:09
OK weird. It was fine for awhile, I was testing some things on staging for 10 or 15 minutes, then suddenly it went back to being on the left side.

**Comment by nnnnat** [comment] 2018-09-10 13:52
I'm pretty sure this issue is being caused by Source Sans font never being loaded on production. I'm pretty sure its related to [this](https://github.com/reactioncommerce/reaction-next-starterkit/issues/215) issue. If you have Source Sans installed locally you won't see an issue.

**Comment by nnnnat** [comment] 2018-09-13 13:28
resolved with PR #275

**Comment by aldeed** [comment] 2018-09-17 17:14
Assigned to @rosshadden since the Material UI update assigned to him may fix this

**Comment by rosshadden** [comment] 2018-09-18 03:03
I updated Material UI in #297, but I haven't seen this issue yet even before doing so. It has been said to be intermittent or perhaps font-dependent, so I will keep an eye out for it.

**Comment by rosshadden** [comment] 2018-09-19 21:52
While testing something else, I had found that this was consistently recreatable:

1) load `/`
2) click `Next`
3) refresh

On another note, it seems to have been fixed by #309.

**Closed** 2018-09-19 22:27 UTC
Labels: bug
