### ISSUE TITLE
Navigation 2.0

### ISSUE THREAD

**Issue by dancastellon** [reactioncommerce/reaction-next-starterkit#427] opened 2018-11-19 20:43 UTC
## Description
[PR #4683](https://github.com/reactioncommerce/reaction/pull/4683) in the Reaction repo introduces a GraphQL API for creating and loading a hierarchical navigation tree that supports both tags and arbitrary menu links.

[Issue #4810](https://github.com/reactioncommerce/reaction/issues/4810) in the Reaction repo describes a UI for operators to define and drag/drop items into a navigation tree.

The last piece would be for starterkit to query the GraphQL API (specifically the `navigationTreeById` query) and build the UI for the new navigation.

**Comment by aldeed** [comment] 2019-01-09 18:58
Closing as duplicate of #446

**Closed by aldeed** 2019-01-09 18:58 UTC
