### ISSUE TITLE
Design Review Epic: PDP - Size options should be a dropdown on mobile

### ISSUE THREAD

**Issue by rosshadden** [reactioncommerce/reaction-next-starterkit#283] opened 2018-09-15 01:50 UTC
Split off from #258.

**Comment by aldeed** [comment] 2018-09-20 12:02
This is probably blocked until we refactor product attributes

**Comment by machikoyasuda** [comment] 2018-11-20 19:06
Closing b/c duplicate of https://github.com/reactioncommerce/reaction-next-starterkit/issues/376

**Closed by machikoyasuda** 2018-11-20 19:06 UTC
