### ISSUE TITLE
Multiple re-renders due to decorators that fetch data using Apollo

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#142] opened 2018-06-12 18:44 UTC
## Issue
The decorators, `withTag` `withCatalogItems` specifically on the tag page, cause the component to rerender twice. This isn't a huge issue in itself; however, add tracking and now we get multiple duplicate events triggered in Segment with different data.

First, the data comes in with all of the products for the page without filtering, then the second event has the list with the filtering by tag.

## Question

Should we start considering ways to combine queries for data for into a single query? This would be more in the spirit of GraphQL by making one request for everything we need for a page. Though, it would mean more bespoke queries that may only have a single

## Reproduction

1. Create a segment account and get the API key. Add the key to the .env (see .env.example)
1. Start the app navigate to a tag grid
1. In the segment dashboard under sources > javascript > debugger see the events being tracked
1. If you refresh the tag page, you should see multiple `Product List Viewed` events being fired, once with all products, once with only the products for that tag page (if you have your data set up in a way that has many products in many tags)

**Comment by spencern** [comment] 2018-06-14 16:18
Needs reproduction steps.

**Comment by aldeed** [comment] 2018-06-25 21:02
Assigned to @kieckhafer to see whether this is still reproducible

**Comment by kieckhafer** [comment] 2018-06-25 22:03
Can confirm this is happening.

**Comment by willopez** [comment] 2018-07-09 16:12
Seems to be a known issue, and a fix has been posted here: https://github.com/zeit/next.js/pull/4734

**Closed** 2018-07-17 18:30 UTC
Labels: bug
