### ISSUE TITLE
Wire up Cart and mini-cart summary

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction-next-starterkit#209] opened 2018-08-07 17:52 UTC
Add the data fetched from the GraphQL API to the summary component for the cart and mini-cart.

**Comment by aldeed** [comment] 2018-08-08 18:29
Seems to be a duplicate of #208

**Comment by mikemurray** [comment] 2018-08-08 18:30
This is specifically for the cart page and mini cart drawer, not the checkout page.

**Comment by aldeed** [comment] 2018-08-08 18:30
Or nevermind, I guess this is for non-checkout summaries. The word "checkout" in the title confused me

**Closed** 2018-08-13 22:33 UTC
